    name: BUILD
    on: push
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        
        - uses: zhullyb/build-aur-action@master
          with:
            repo-name: microsoft-edge-beta-bin

        - uses: ncipollo/release-action@v1.6.1
          with:
            allowUpdates: true
            tag: "out"
            artifacts: "./*/*.zst"
            token: ${{ secrets.GITHUB_TOKEN }}
